export const defaultData = [
  [
    "镜头号",
    "画面场景",
    "画面描述",
    "使用Midjourney生成角色所需提示词",
    "诗句/台词旁白",
    "根据台词旁白评估镜头占用时间",
  ],
  [
    "1",
    "画面中展示古诗的名称、朝代、诗人",
    "窗口框显示“山行，唐，杜牧”字样。",
    "classroom scene, child character waving, large window with characters '山行'",
    "山行，唐，杜牧。",
    "00:00-00:04",
  ],
  [
    "2",
    "山间石路",
    "一辆马车在弯曲的山间石路上缓缓行驶，山间景色宁静，秋色迷人。",
    "carriage on mountain path, autumn scenery, tranquil environment",
    "远上寒山石径斜。",
    "00:04-00:10",
  ],
  [
    "3",
    "山中远景",
    "远处山间云雾缭绕，几座房屋隐约可见，仿佛与白云融为一体。",
    "distant mountain houses, misty environment, autumn clouds",
    "白云生处有人家。",
    "00:10-00:14",
  ],
  [
    "4",
    "杜牧看向远方",
    "杜牧从马车中探出头，凝视远方的枫林，脸上露出惊喜的表情。",
    "ancient poet in carriage, joyful expression, looking at forest",
    "停车坐爱枫林晚",
    "00:14-00:18",
  ],
  [
    "5",
    "枫叶的特写",
    "红艳的枫叶在秋日阳光的照耀下，呈现出鲜红色，极其美丽。",
    "close-up of red maple leaves, vibrant autumn colors",
    "霜叶红于二月花。",
    "00:18-00:22",
  ],
  [
    "6",
    "山中秋景",
    "杜牧站在马车旁，欣喜地望着枫林景色，马车停在一旁，画面唯美。",
    "ancient poet standing next to carriage, admiring autumn scenery",
    "这首诗描绘了诗人杜牧在深秋时节，行走山间时看到的美丽景色。",
    "00:22-00:26",
  ],
  [
    "7",
    "诗句画面展示",
    "屏幕中显示“远上寒山石径斜，白云生处有人家。”，其中“生”字高亮，并解释为“产生”。",
    "highlighted Chinese character with explanation, traditional script",
    "“远上寒山石径斜，白云生处有人家。”“生”，是产生的意思。",
    "00:26-00:30",
  ],
  [
    "8",
    "山中马车沿石路前行",
    "马车沿着弯曲的石路向山中行驶，杜牧探出头向远处望去，背景是云雾缭绕的山景。",
    "carriage on winding path, misty mountains, poet looking out",
    "沿着弯弯曲曲的石路登上寒意正浓的山，在那生出白云的地方，居然还有几户人家。",
    "00:30-00:34",
  ],
  [
    "9",
    "诗句画面展示",
    "屏幕中显示“停车坐爱枫林晚，霜叶红于二月花。”，其中“坐”字高亮，并解释为“因为”。",
    "highlighted Chinese character with explanation, traditional script",
    "“停车坐爱枫林晚，霜叶红于二月花。”“坐”，是因为的意思。",
    "00:34-00:38",
  ],
  [
    "10",
    "马车停在枫林前",
    "马车停下，杜牧跳下车，向前走几步，看着眼前的枫林，满脸欣喜。",
    "carriage stopped at forest, poet jumping out, excited expression",
    "停下马车是因为喜欢深秋枫林的晚景，枫叶比二月的春花还要红艳。",
    "00:38-00:42",
  ],
  [
    "11",
    "枫叶的特写",
    "枫叶的特写，红艳的叶片在微风中轻轻摇曳，秋天的阳光透过叶片洒在地上。",
    "close-up of red maple leaves, sunlight filtering through",
    "",
    "00:42-00:46",
  ],
];
